name: Discord
on:
  pull_request:
  
  push: 
    branches:
      'main'
  workflow_dispatch:

jobs:
  test-on-gha:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: create .env file
        run: |
          cat <<EOL > .env
          token=${{ secrets.DISCORD_TOKEN }}
          clientID=${{ secrets.CLIENT_ID }}
          guildID=${{ secrets.GUILD_ID }}
          channelID=${{secrets.CHANNEL_ID}}
          EOL
      
      - name: install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: install dependencies
        uses: ./.github/actions/npm-install

      - name: build env
        shell: bash
        run: npm run test